// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exchanges.proto

package exchanges

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Exchange struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Periods              []string `protobuf:"bytes,2,rep,name=periods,proto3" json:"periods,omitempty"`
	Pairs                []string `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
	Fees                 float32  `protobuf:"fixed32,4,opt,name=fees,proto3" json:"fees,omitempty"`
	LastSyncTime         string   `protobuf:"bytes,5,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exchange) Reset()         { *m = Exchange{} }
func (m *Exchange) String() string { return proto.CompactTextString(m) }
func (*Exchange) ProtoMessage()    {}
func (*Exchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_48af87575be74460, []int{0}
}

func (m *Exchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exchange.Unmarshal(m, b)
}
func (m *Exchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exchange.Marshal(b, m, deterministic)
}
func (m *Exchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exchange.Merge(m, src)
}
func (m *Exchange) XXX_Size() int {
	return xxx_messageInfo_Exchange.Size(m)
}
func (m *Exchange) XXX_DiscardUnknown() {
	xxx_messageInfo_Exchange.DiscardUnknown(m)
}

var xxx_messageInfo_Exchange proto.InternalMessageInfo

func (m *Exchange) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Exchange) GetPeriods() []string {
	if m != nil {
		return m.Periods
	}
	return nil
}

func (m *Exchange) GetPairs() []string {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *Exchange) GetFees() float32 {
	if m != nil {
		return m.Fees
	}
	return 0
}

func (m *Exchange) GetLastSyncTime() string {
	if m != nil {
		return m.LastSyncTime
	}
	return ""
}

type ReadExchangesRequest struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadExchangesRequest) Reset()         { *m = ReadExchangesRequest{} }
func (m *ReadExchangesRequest) String() string { return proto.CompactTextString(m) }
func (*ReadExchangesRequest) ProtoMessage()    {}
func (*ReadExchangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48af87575be74460, []int{1}
}

func (m *ReadExchangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadExchangesRequest.Unmarshal(m, b)
}
func (m *ReadExchangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadExchangesRequest.Marshal(b, m, deterministic)
}
func (m *ReadExchangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadExchangesRequest.Merge(m, src)
}
func (m *ReadExchangesRequest) XXX_Size() int {
	return xxx_messageInfo_ReadExchangesRequest.Size(m)
}
func (m *ReadExchangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadExchangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadExchangesRequest proto.InternalMessageInfo

func (m *ReadExchangesRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type ReadExchangesResponse struct {
	Exchanges            []*Exchange `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadExchangesResponse) Reset()         { *m = ReadExchangesResponse{} }
func (m *ReadExchangesResponse) String() string { return proto.CompactTextString(m) }
func (*ReadExchangesResponse) ProtoMessage()    {}
func (*ReadExchangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48af87575be74460, []int{2}
}

func (m *ReadExchangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadExchangesResponse.Unmarshal(m, b)
}
func (m *ReadExchangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadExchangesResponse.Marshal(b, m, deterministic)
}
func (m *ReadExchangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadExchangesResponse.Merge(m, src)
}
func (m *ReadExchangesResponse) XXX_Size() int {
	return xxx_messageInfo_ReadExchangesResponse.Size(m)
}
func (m *ReadExchangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadExchangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadExchangesResponse proto.InternalMessageInfo

func (m *ReadExchangesResponse) GetExchanges() []*Exchange {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

func init() {
	proto.RegisterType((*Exchange)(nil), "exchanges.Exchange")
	proto.RegisterType((*ReadExchangesRequest)(nil), "exchanges.ReadExchangesRequest")
	proto.RegisterType((*ReadExchangesResponse)(nil), "exchanges.ReadExchangesResponse")
}

func init() { proto.RegisterFile("exchanges.proto", fileDescriptor_48af87575be74460) }

var fileDescriptor_48af87575be74460 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcb, 0x4e, 0x83, 0x40,
	0x14, 0x75, 0xfa, 0x50, 0x7b, 0x7d, 0xe6, 0x5a, 0xe3, 0xe8, 0x46, 0x42, 0x5c, 0xb0, 0x30, 0x25,
	0xd6, 0x3f, 0x30, 0x71, 0xe3, 0x72, 0xda, 0x95, 0x9b, 0x66, 0xa4, 0x57, 0x3a, 0x51, 0x86, 0x91,
	0x8b, 0xc6, 0xfe, 0x81, 0x9f, 0x6d, 0x18, 0x04, 0xd4, 0xe8, 0xee, 0x9e, 0x93, 0xf3, 0x82, 0x81,
	0x03, 0x7a, 0x4f, 0x56, 0xda, 0xa6, 0xc4, 0x13, 0x57, 0xe4, 0x65, 0x8e, 0xa3, 0x96, 0x08, 0x3f,
	0x04, 0x6c, 0xdf, 0x7e, 0x21, 0x44, 0x18, 0x58, 0x9d, 0x91, 0x14, 0x81, 0x88, 0x46, 0xca, 0xdf,
	0x28, 0x61, 0xcb, 0x51, 0x61, 0xf2, 0x25, 0xcb, 0x5e, 0xd0, 0x8f, 0x46, 0xaa, 0x81, 0x38, 0x86,
	0xa1, 0xd3, 0xa6, 0x60, 0xd9, 0xf7, 0x7c, 0x0d, 0xaa, 0x8c, 0x47, 0x22, 0x96, 0x83, 0x40, 0x44,
	0x3d, 0xe5, 0x6f, 0xbc, 0x80, 0xfd, 0x67, 0xcd, 0xe5, 0x82, 0xd7, 0x36, 0x59, 0x94, 0x26, 0x23,
	0x39, 0xf4, 0x0d, 0xbb, 0x15, 0x3b, 0x5b, 0xdb, 0x64, 0x6e, 0x32, 0x0a, 0x2f, 0x61, 0xac, 0x48,
	0x2f, 0x9b, 0x35, 0xac, 0xe8, 0xe5, 0x95, 0xb8, 0xac, 0x7a, 0xaa, 0x25, 0x2c, 0x45, 0xdd, 0xe3,
	0x41, 0x78, 0x07, 0xc7, 0xbf, 0xd4, 0xec, 0x72, 0xcb, 0x84, 0x57, 0xd0, 0x7d, 0x9e, 0xb7, 0xec,
	0x4c, 0x8f, 0x26, 0xdd, 0x1f, 0x68, 0x0c, 0xaa, 0x53, 0x4d, 0x57, 0x70, 0xd8, 0xe6, 0xcc, 0xa8,
	0x78, 0x33, 0x09, 0xe1, 0x1c, 0xf6, 0x7e, 0xe4, 0xe3, 0xf9, 0xb7, 0x90, 0xbf, 0x76, 0x9e, 0x05,
	0xff, 0x0b, 0xea, 0x69, 0xe1, 0xc6, 0xcd, 0xe9, 0xfd, 0x49, 0xec, 0x9e, 0xd2, 0x38, 0x25, 0xeb,
	0x9f, 0x22, 0x6e, 0x2d, 0x0f, 0x9b, 0x9e, 0xb8, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xe6,
	0x4d, 0xe8, 0xae, 0x01, 0x00, 0x00,
}
