version: '3'
services:
  cockroachdb:
      image: cockroachdb/cockroach
      ports:
          - 26257:26257
          - 26256:8080
      networks:
          - cryptellation-network
      ulimits:
          nofile:
              soft: 65536
              hard: 65536
      command: start-single-node --insecure
  redis:
      image: redis:alpine
      hostname: redis
      networks:
          - cryptellation-network
  exchanges:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9002:9002
    env_file:
      - configs/env/.env
    environment:
      - COCKROACHDB_DATABASE=exchanges
      - SERVICE_PORT=9002
    depends_on:
      - cockroachdb
    networks:
      - cryptellation-network
    command: [ "go", "run", "./services/exchanges/cmd/exchanges-server/main.go" ]
  candlesticks:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9003:9003
    env_file:
      - configs/env/.env
    environment:
      - COCKROACHDB_DATABASE=candlesticks
      - SERVICE_PORT=9003
    depends_on:
      - cockroachdb
    networks:
      - cryptellation-network
    command: [ "go", "run", "./services/candlesticks/cmd/candlesticks-server/main.go" ]
  backtests:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9004:9004
    env_file:
      - configs/env/.env
    environment:
      - SERVICE_PORT=9004
    depends_on:
      - redis
      - candlesticks
    networks:
      - cryptellation-network
    command: [ "go", "run", "./services/backtests/cmd/backtests-server/main.go" ]
  ticks:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    volumes:
      - .:/code
      - /root/.cache/go-build
    working_dir: /code
    ports:
      - 127.0.0.1:9005:9005
    env_file:
      - configs/env/.env
    environment:
      - SERVICE_PORT=9005
    depends_on:
      - redis
    networks:
      - cryptellation-network
    command: [ "go", "run", "./services/ticks/cmd/ticks-server/main.go" ]
networks:
    cryptellation-network: