// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backtests.proto

package backtests

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	ExchangeName         string             `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	Assets               map[string]float32 `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *Account) GetAssets() map[string]float32 {
	if m != nil {
		return m.Assets
	}
	return nil
}

type CreateBacktestRequest struct {
	Accounts                  []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	StartTime                 string     `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                   string     `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SecondsBetweenPriceEvents uint64     `protobuf:"varint,4,opt,name=seconds_between_price_events,json=secondsBetweenPriceEvents,proto3" json:"seconds_between_price_events,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}   `json:"-"`
	XXX_unrecognized          []byte     `json:"-"`
	XXX_sizecache             int32      `json:"-"`
}

func (m *CreateBacktestRequest) Reset()         { *m = CreateBacktestRequest{} }
func (m *CreateBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestRequest) ProtoMessage()    {}
func (*CreateBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{1}
}

func (m *CreateBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestRequest.Unmarshal(m, b)
}
func (m *CreateBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestRequest.Marshal(b, m, deterministic)
}
func (m *CreateBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestRequest.Merge(m, src)
}
func (m *CreateBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestRequest.Size(m)
}
func (m *CreateBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestRequest proto.InternalMessageInfo

func (m *CreateBacktestRequest) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *CreateBacktestRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreateBacktestRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CreateBacktestRequest) GetSecondsBetweenPriceEvents() uint64 {
	if m != nil {
		return m.SecondsBetweenPriceEvents
	}
	return 0
}

type CreateBacktestResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBacktestResponse) Reset()         { *m = CreateBacktestResponse{} }
func (m *CreateBacktestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestResponse) ProtoMessage()    {}
func (*CreateBacktestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{2}
}

func (m *CreateBacktestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestResponse.Unmarshal(m, b)
}
func (m *CreateBacktestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestResponse.Marshal(b, m, deterministic)
}
func (m *CreateBacktestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestResponse.Merge(m, src)
}
func (m *CreateBacktestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestResponse.Size(m)
}
func (m *CreateBacktestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestResponse proto.InternalMessageInfo

func (m *CreateBacktestResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SubscribeToBacktestEventsRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExchangeName         string   `protobuf:"bytes,2,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	PairSymbol           string   `protobuf:"bytes,3,opt,name=pair_symbol,json=pairSymbol,proto3" json:"pair_symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToBacktestEventsRequest) Reset()         { *m = SubscribeToBacktestEventsRequest{} }
func (m *SubscribeToBacktestEventsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToBacktestEventsRequest) ProtoMessage()    {}
func (*SubscribeToBacktestEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{3}
}

func (m *SubscribeToBacktestEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToBacktestEventsRequest.Unmarshal(m, b)
}
func (m *SubscribeToBacktestEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToBacktestEventsRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeToBacktestEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToBacktestEventsRequest.Merge(m, src)
}
func (m *SubscribeToBacktestEventsRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToBacktestEventsRequest.Size(m)
}
func (m *SubscribeToBacktestEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToBacktestEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToBacktestEventsRequest proto.InternalMessageInfo

func (m *SubscribeToBacktestEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubscribeToBacktestEventsRequest) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *SubscribeToBacktestEventsRequest) GetPairSymbol() string {
	if m != nil {
		return m.PairSymbol
	}
	return ""
}

type SubscribeToBacktestEventsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToBacktestEventsResponse) Reset()         { *m = SubscribeToBacktestEventsResponse{} }
func (m *SubscribeToBacktestEventsResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeToBacktestEventsResponse) ProtoMessage()    {}
func (*SubscribeToBacktestEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{4}
}

func (m *SubscribeToBacktestEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToBacktestEventsResponse.Unmarshal(m, b)
}
func (m *SubscribeToBacktestEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToBacktestEventsResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeToBacktestEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToBacktestEventsResponse.Merge(m, src)
}
func (m *SubscribeToBacktestEventsResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeToBacktestEventsResponse.Size(m)
}
func (m *SubscribeToBacktestEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToBacktestEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToBacktestEventsResponse proto.InternalMessageInfo

type AdvanceBacktestRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvanceBacktestRequest) Reset()         { *m = AdvanceBacktestRequest{} }
func (m *AdvanceBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*AdvanceBacktestRequest) ProtoMessage()    {}
func (*AdvanceBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{5}
}

func (m *AdvanceBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvanceBacktestRequest.Unmarshal(m, b)
}
func (m *AdvanceBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvanceBacktestRequest.Marshal(b, m, deterministic)
}
func (m *AdvanceBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvanceBacktestRequest.Merge(m, src)
}
func (m *AdvanceBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_AdvanceBacktestRequest.Size(m)
}
func (m *AdvanceBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvanceBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdvanceBacktestRequest proto.InternalMessageInfo

func (m *AdvanceBacktestRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AdvanceBacktestResponse struct {
	Finished             bool     `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvanceBacktestResponse) Reset()         { *m = AdvanceBacktestResponse{} }
func (m *AdvanceBacktestResponse) String() string { return proto.CompactTextString(m) }
func (*AdvanceBacktestResponse) ProtoMessage()    {}
func (*AdvanceBacktestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{6}
}

func (m *AdvanceBacktestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvanceBacktestResponse.Unmarshal(m, b)
}
func (m *AdvanceBacktestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvanceBacktestResponse.Marshal(b, m, deterministic)
}
func (m *AdvanceBacktestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvanceBacktestResponse.Merge(m, src)
}
func (m *AdvanceBacktestResponse) XXX_Size() int {
	return xxx_messageInfo_AdvanceBacktestResponse.Size(m)
}
func (m *AdvanceBacktestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvanceBacktestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdvanceBacktestResponse proto.InternalMessageInfo

func (m *AdvanceBacktestResponse) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

type ListenBacktestRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenBacktestRequest) Reset()         { *m = ListenBacktestRequest{} }
func (m *ListenBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*ListenBacktestRequest) ProtoMessage()    {}
func (*ListenBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{7}
}

func (m *ListenBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenBacktestRequest.Unmarshal(m, b)
}
func (m *ListenBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenBacktestRequest.Marshal(b, m, deterministic)
}
func (m *ListenBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenBacktestRequest.Merge(m, src)
}
func (m *ListenBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_ListenBacktestRequest.Size(m)
}
func (m *ListenBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenBacktestRequest proto.InternalMessageInfo

func (m *ListenBacktestRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{8}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Event) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateBacktestOrderRequest struct {
	BacktestId           uint64   `protobuf:"varint,1,opt,name=backtest_id,json=backtestId,proto3" json:"backtest_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ExchangeName         string   `protobuf:"bytes,3,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	PairSymbol           string   `protobuf:"bytes,4,opt,name=pair_symbol,json=pairSymbol,proto3" json:"pair_symbol,omitempty"`
	Side                 string   `protobuf:"bytes,5,opt,name=side,proto3" json:"side,omitempty"`
	Quantity             float32  `protobuf:"fixed32,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBacktestOrderRequest) Reset()         { *m = CreateBacktestOrderRequest{} }
func (m *CreateBacktestOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestOrderRequest) ProtoMessage()    {}
func (*CreateBacktestOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{9}
}

func (m *CreateBacktestOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestOrderRequest.Unmarshal(m, b)
}
func (m *CreateBacktestOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateBacktestOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestOrderRequest.Merge(m, src)
}
func (m *CreateBacktestOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestOrderRequest.Size(m)
}
func (m *CreateBacktestOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestOrderRequest proto.InternalMessageInfo

func (m *CreateBacktestOrderRequest) GetBacktestId() uint64 {
	if m != nil {
		return m.BacktestId
	}
	return 0
}

func (m *CreateBacktestOrderRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateBacktestOrderRequest) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *CreateBacktestOrderRequest) GetPairSymbol() string {
	if m != nil {
		return m.PairSymbol
	}
	return ""
}

func (m *CreateBacktestOrderRequest) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *CreateBacktestOrderRequest) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateBacktestOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBacktestOrderResponse) Reset()         { *m = CreateBacktestOrderResponse{} }
func (m *CreateBacktestOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestOrderResponse) ProtoMessage()    {}
func (*CreateBacktestOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{10}
}

func (m *CreateBacktestOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestOrderResponse.Unmarshal(m, b)
}
func (m *CreateBacktestOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateBacktestOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestOrderResponse.Merge(m, src)
}
func (m *CreateBacktestOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestOrderResponse.Size(m)
}
func (m *CreateBacktestOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestOrderResponse proto.InternalMessageInfo

type AccountsRequest struct {
	BacktestId           uint64   `protobuf:"varint,1,opt,name=backtest_id,json=backtestId,proto3" json:"backtest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountsRequest) Reset()         { *m = AccountsRequest{} }
func (m *AccountsRequest) String() string { return proto.CompactTextString(m) }
func (*AccountsRequest) ProtoMessage()    {}
func (*AccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{11}
}

func (m *AccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsRequest.Unmarshal(m, b)
}
func (m *AccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsRequest.Marshal(b, m, deterministic)
}
func (m *AccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsRequest.Merge(m, src)
}
func (m *AccountsRequest) XXX_Size() int {
	return xxx_messageInfo_AccountsRequest.Size(m)
}
func (m *AccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsRequest proto.InternalMessageInfo

func (m *AccountsRequest) GetBacktestId() uint64 {
	if m != nil {
		return m.BacktestId
	}
	return 0
}

type AccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountsResponse) Reset()         { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()    {}
func (*AccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{12}
}

func (m *AccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsResponse.Unmarshal(m, b)
}
func (m *AccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsResponse.Marshal(b, m, deterministic)
}
func (m *AccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsResponse.Merge(m, src)
}
func (m *AccountsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsResponse.Size(m)
}
func (m *AccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsResponse proto.InternalMessageInfo

func (m *AccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "backtests.Account")
	proto.RegisterMapType((map[string]float32)(nil), "backtests.Account.AssetsEntry")
	proto.RegisterType((*CreateBacktestRequest)(nil), "backtests.CreateBacktestRequest")
	proto.RegisterType((*CreateBacktestResponse)(nil), "backtests.CreateBacktestResponse")
	proto.RegisterType((*SubscribeToBacktestEventsRequest)(nil), "backtests.SubscribeToBacktestEventsRequest")
	proto.RegisterType((*SubscribeToBacktestEventsResponse)(nil), "backtests.SubscribeToBacktestEventsResponse")
	proto.RegisterType((*AdvanceBacktestRequest)(nil), "backtests.AdvanceBacktestRequest")
	proto.RegisterType((*AdvanceBacktestResponse)(nil), "backtests.AdvanceBacktestResponse")
	proto.RegisterType((*ListenBacktestRequest)(nil), "backtests.ListenBacktestRequest")
	proto.RegisterType((*Event)(nil), "backtests.Event")
	proto.RegisterType((*CreateBacktestOrderRequest)(nil), "backtests.CreateBacktestOrderRequest")
	proto.RegisterType((*CreateBacktestOrderResponse)(nil), "backtests.CreateBacktestOrderResponse")
	proto.RegisterType((*AccountsRequest)(nil), "backtests.AccountsRequest")
	proto.RegisterType((*AccountsResponse)(nil), "backtests.AccountsResponse")
}

func init() { proto.RegisterFile("backtests.proto", fileDescriptor_f20790a094d31fce) }

var fileDescriptor_f20790a094d31fce = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x51, 0x4f, 0xd3, 0x50,
	0x14, 0xa6, 0xdd, 0x80, 0xed, 0x4c, 0x61, 0xb9, 0x8a, 0x74, 0x45, 0x64, 0x94, 0xa8, 0x4b, 0x34,
	0xc3, 0x60, 0x34, 0xea, 0x8b, 0x61, 0x86, 0x44, 0x12, 0xa3, 0xa6, 0x90, 0x98, 0xf0, 0xd2, 0xdc,
	0xb5, 0x07, 0xb8, 0x81, 0xdd, 0x8e, 0xde, 0xbb, 0xc9, 0x7e, 0x8e, 0x7f, 0xc3, 0x47, 0x5f, 0xfc,
	0x5b, 0xa6, 0xb7, 0xb7, 0xa5, 0xdb, 0xca, 0x86, 0x6f, 0xf7, 0x9e, 0xfb, 0xf5, 0x9c, 0xef, 0x3b,
	0xdf, 0x39, 0x29, 0xac, 0x76, 0xa9, 0x7f, 0x21, 0x51, 0x48, 0xd1, 0xee, 0x47, 0xa1, 0x0c, 0x49,
	0x35, 0x0b, 0x38, 0xbf, 0x0c, 0x58, 0xde, 0xf7, 0xfd, 0x70, 0xc0, 0x25, 0xd9, 0x81, 0xfb, 0x78,
	0xed, 0x9f, 0x53, 0x7e, 0x86, 0x1e, 0xa7, 0x3d, 0xb4, 0x8c, 0xa6, 0xd1, 0xaa, 0xba, 0xf7, 0xd2,
	0xe0, 0x57, 0xda, 0x43, 0xf2, 0x16, 0x96, 0xa8, 0x10, 0x28, 0x85, 0x65, 0x36, 0x4b, 0xad, 0xda,
	0xde, 0x93, 0xf6, 0x4d, 0x76, 0x9d, 0xa8, 0xbd, 0xaf, 0x00, 0x07, 0x5c, 0x46, 0x23, 0x57, 0xa3,
	0xed, 0xf7, 0x50, 0xcb, 0x85, 0x49, 0x1d, 0x4a, 0x17, 0x38, 0xd2, 0x15, 0xe2, 0x23, 0x79, 0x08,
	0x8b, 0x43, 0x7a, 0x39, 0x40, 0xcb, 0x6c, 0x1a, 0x2d, 0xd3, 0x4d, 0x2e, 0x1f, 0xcc, 0x77, 0x86,
	0xf3, 0xc7, 0x80, 0xb5, 0x4f, 0x11, 0x52, 0x89, 0x1d, 0x5d, 0xca, 0xc5, 0xab, 0x01, 0x0a, 0x49,
	0xda, 0x50, 0xa1, 0x49, 0x4d, 0x61, 0x19, 0x8a, 0x0e, 0x99, 0xa6, 0xe3, 0x66, 0x18, 0xb2, 0x09,
	0x20, 0x24, 0x8d, 0xa4, 0x27, 0x59, 0x2f, 0x29, 0x54, 0x75, 0xab, 0x2a, 0x72, 0xcc, 0x7a, 0x48,
	0x1a, 0x50, 0x41, 0x1e, 0x24, 0x8f, 0x25, 0xf5, 0xb8, 0x8c, 0x3c, 0x50, 0x4f, 0x1f, 0xe1, 0xb1,
	0x40, 0x3f, 0xe4, 0x81, 0xf0, 0xba, 0x28, 0x7f, 0x22, 0x72, 0xaf, 0x1f, 0x31, 0x1f, 0x3d, 0x1c,
	0x62, 0x5c, 0xbd, 0xdc, 0x34, 0x5a, 0x65, 0xb7, 0xa1, 0x31, 0x9d, 0x04, 0xf2, 0x3d, 0x46, 0x1c,
	0x28, 0x80, 0xd3, 0x82, 0x47, 0x93, 0x1a, 0x44, 0x3f, 0xe4, 0x02, 0xc9, 0x0a, 0x98, 0x2c, 0x50,
	0x9d, 0x28, 0xbb, 0x26, 0x0b, 0x9c, 0x6b, 0x68, 0x1e, 0x0d, 0xba, 0xc2, 0x8f, 0x58, 0x17, 0x8f,
	0xc3, 0x14, 0x9e, 0xa4, 0x49, 0x85, 0x4f, 0x7c, 0x33, 0x6d, 0x9d, 0x59, 0x60, 0xdd, 0x16, 0xd4,
	0xfa, 0x94, 0x45, 0x9e, 0x18, 0xf5, 0xba, 0xe1, 0xa5, 0x56, 0x08, 0x71, 0xe8, 0x48, 0x45, 0x9c,
	0x1d, 0xd8, 0x9e, 0x51, 0x39, 0xa1, 0x1b, 0x0b, 0xd9, 0x0f, 0x86, 0x94, 0xfb, 0x53, 0x6e, 0x4c,
	0x0a, 0x79, 0x03, 0xeb, 0x53, 0x48, 0xad, 0xd9, 0x86, 0xca, 0x29, 0xe3, 0x4c, 0x9c, 0x63, 0xf2,
	0x41, 0xc5, 0xcd, 0xee, 0xce, 0x73, 0x58, 0xfb, 0xc2, 0x84, 0x44, 0x3e, 0x2f, 0xff, 0x21, 0x2c,
	0x2a, 0x6e, 0x84, 0x40, 0x59, 0x8e, 0xfa, 0xe9, 0xbc, 0xaa, 0xb3, 0x8a, 0xdd, 0x98, 0xac, 0xce,
	0xc4, 0x82, 0x65, 0x3f, 0xe4, 0x12, 0xb9, 0x4c, 0xed, 0xd5, 0x57, 0xe7, 0xaf, 0x01, 0xf6, 0xb8,
	0x3d, 0xdf, 0xa2, 0x00, 0xa3, 0xb4, 0xf2, 0x16, 0xd4, 0xd2, 0xb1, 0xf2, 0x32, 0x0a, 0x90, 0x86,
	0x0e, 0x83, 0x8c, 0x81, 0x99, 0x63, 0x30, 0xe5, 0x49, 0x69, 0xbe, 0x27, 0xe5, 0x49, 0x4f, 0xe2,
	0xcc, 0x82, 0x05, 0x68, 0x2d, 0x26, 0x99, 0xe3, 0x73, 0xdc, 0xbd, 0xab, 0x01, 0xe5, 0x92, 0xc9,
	0x91, 0xb5, 0xa4, 0xb6, 0x25, 0xbb, 0x3b, 0x9b, 0xb0, 0x51, 0x28, 0x44, 0xbb, 0xb7, 0x07, 0xab,
	0x7a, 0x2d, 0xc4, 0x5d, 0xc5, 0x39, 0x1d, 0xa8, 0xdf, 0x7c, 0xa3, 0x0d, 0xfc, 0xcf, 0xcd, 0xdb,
	0xfb, 0x5d, 0x86, 0x7a, 0xca, 0x48, 0x1c, 0x61, 0x34, 0x64, 0x3e, 0x92, 0x1f, 0xb0, 0x32, 0xce,
	0x95, 0x34, 0x73, 0x49, 0x0a, 0x57, 0xde, 0xde, 0x9e, 0x81, 0xd0, 0x1a, 0x17, 0xc8, 0x35, 0x34,
	0x6e, 0x1d, 0x64, 0xf2, 0x22, 0x97, 0x61, 0xde, 0xa2, 0xd9, 0x2f, 0xef, 0x06, 0xce, 0x2a, 0x7f,
	0x86, 0x95, 0xf1, 0xe1, 0x1d, 0x93, 0x54, 0x38, 0xd7, 0x76, 0x3d, 0x87, 0x50, 0x09, 0x9d, 0x85,
	0x57, 0x06, 0x39, 0x81, 0xd5, 0x89, 0xed, 0x21, 0x79, 0xed, 0xc5, 0x3b, 0x68, 0x3b, 0xb3, 0x20,
	0x19, 0xcb, 0x53, 0x78, 0x50, 0x30, 0x24, 0xe4, 0xe9, 0xad, 0xbd, 0xcd, 0x6f, 0x83, 0xfd, 0x6c,
	0x1e, 0x2c, 0xab, 0x73, 0x00, 0x95, 0x74, 0x72, 0x88, 0x3d, 0x3d, 0x1f, 0x59, 0x97, 0x37, 0x0a,
	0xdf, 0xd2, 0x34, 0x9d, 0xc6, 0xc9, 0xfa, 0x6e, 0xff, 0xe2, 0x6c, 0xf7, 0x0c, 0xb9, 0xfa, 0x81,
	0xed, 0x66, 0xe8, 0xee, 0x92, 0x0a, 0xbc, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xa7, 0xf6,
	0xa3, 0xe4, 0x06, 0x00, 0x00,
}
