// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: backtests.proto

package backtests

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BacktestsServiceClient is the client API for BacktestsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BacktestsServiceClient interface {
	CreateBacktest(ctx context.Context, in *CreateBacktestRequest, opts ...grpc.CallOption) (*CreateBacktestResponse, error)
}

type backtestsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBacktestsServiceClient(cc grpc.ClientConnInterface) BacktestsServiceClient {
	return &backtestsServiceClient{cc}
}

func (c *backtestsServiceClient) CreateBacktest(ctx context.Context, in *CreateBacktestRequest, opts ...grpc.CallOption) (*CreateBacktestResponse, error) {
	out := new(CreateBacktestResponse)
	err := c.cc.Invoke(ctx, "/backtests.BacktestsService/CreateBacktest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BacktestsServiceServer is the server API for BacktestsService service.
// All implementations should embed UnimplementedBacktestsServiceServer
// for forward compatibility
type BacktestsServiceServer interface {
	CreateBacktest(context.Context, *CreateBacktestRequest) (*CreateBacktestResponse, error)
}

// UnimplementedBacktestsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBacktestsServiceServer struct {
}

func (UnimplementedBacktestsServiceServer) CreateBacktest(context.Context, *CreateBacktestRequest) (*CreateBacktestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBacktest not implemented")
}

// UnsafeBacktestsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BacktestsServiceServer will
// result in compilation errors.
type UnsafeBacktestsServiceServer interface {
	mustEmbedUnimplementedBacktestsServiceServer()
}

func RegisterBacktestsServiceServer(s grpc.ServiceRegistrar, srv BacktestsServiceServer) {
	s.RegisterService(&BacktestsService_ServiceDesc, srv)
}

func _BacktestsService_CreateBacktest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBacktestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestsServiceServer).CreateBacktest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backtests.BacktestsService/CreateBacktest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestsServiceServer).CreateBacktest(ctx, req.(*CreateBacktestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BacktestsService_ServiceDesc is the grpc.ServiceDesc for BacktestsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BacktestsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backtests.BacktestsService",
	HandlerType: (*BacktestsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBacktest",
			Handler:    _BacktestsService_CreateBacktest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backtests.proto",
}
