// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backtests.proto

package backtests

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AssetQuantity struct {
	AssetName            string   `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Quantity             float32  `protobuf:"fixed32,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetQuantity) Reset()         { *m = AssetQuantity{} }
func (m *AssetQuantity) String() string { return proto.CompactTextString(m) }
func (*AssetQuantity) ProtoMessage()    {}
func (*AssetQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{0}
}

func (m *AssetQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetQuantity.Unmarshal(m, b)
}
func (m *AssetQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetQuantity.Marshal(b, m, deterministic)
}
func (m *AssetQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetQuantity.Merge(m, src)
}
func (m *AssetQuantity) XXX_Size() int {
	return xxx_messageInfo_AssetQuantity.Size(m)
}
func (m *AssetQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_AssetQuantity proto.InternalMessageInfo

func (m *AssetQuantity) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *AssetQuantity) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Account struct {
	ExchangeName         string           `protobuf:"bytes,1,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	Assets               []*AssetQuantity `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetExchangeName() string {
	if m != nil {
		return m.ExchangeName
	}
	return ""
}

func (m *Account) GetAssets() []*AssetQuantity {
	if m != nil {
		return m.Assets
	}
	return nil
}

type CreateBacktestRequest struct {
	Accounts                  []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	StartTime                 string     `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                   string     `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SecondsBetweenPriceEvents uint64     `protobuf:"varint,4,opt,name=seconds_between_price_events,json=secondsBetweenPriceEvents,proto3" json:"seconds_between_price_events,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}   `json:"-"`
	XXX_unrecognized          []byte     `json:"-"`
	XXX_sizecache             int32      `json:"-"`
}

func (m *CreateBacktestRequest) Reset()         { *m = CreateBacktestRequest{} }
func (m *CreateBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestRequest) ProtoMessage()    {}
func (*CreateBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{2}
}

func (m *CreateBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestRequest.Unmarshal(m, b)
}
func (m *CreateBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestRequest.Marshal(b, m, deterministic)
}
func (m *CreateBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestRequest.Merge(m, src)
}
func (m *CreateBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestRequest.Size(m)
}
func (m *CreateBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestRequest proto.InternalMessageInfo

func (m *CreateBacktestRequest) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *CreateBacktestRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreateBacktestRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CreateBacktestRequest) GetSecondsBetweenPriceEvents() uint64 {
	if m != nil {
		return m.SecondsBetweenPriceEvents
	}
	return 0
}

type CreateBacktestResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBacktestResponse) Reset()         { *m = CreateBacktestResponse{} }
func (m *CreateBacktestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestResponse) ProtoMessage()    {}
func (*CreateBacktestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{3}
}

func (m *CreateBacktestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestResponse.Unmarshal(m, b)
}
func (m *CreateBacktestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestResponse.Marshal(b, m, deterministic)
}
func (m *CreateBacktestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestResponse.Merge(m, src)
}
func (m *CreateBacktestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestResponse.Size(m)
}
func (m *CreateBacktestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestResponse proto.InternalMessageInfo

func (m *CreateBacktestResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SubscribeToBacktestEventsRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	PairSymbol           string   `protobuf:"bytes,3,opt,name=pair_symbol,json=pairSymbol,proto3" json:"pair_symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToBacktestEventsRequest) Reset()         { *m = SubscribeToBacktestEventsRequest{} }
func (m *SubscribeToBacktestEventsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeToBacktestEventsRequest) ProtoMessage()    {}
func (*SubscribeToBacktestEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{4}
}

func (m *SubscribeToBacktestEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToBacktestEventsRequest.Unmarshal(m, b)
}
func (m *SubscribeToBacktestEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToBacktestEventsRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeToBacktestEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToBacktestEventsRequest.Merge(m, src)
}
func (m *SubscribeToBacktestEventsRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeToBacktestEventsRequest.Size(m)
}
func (m *SubscribeToBacktestEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToBacktestEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToBacktestEventsRequest proto.InternalMessageInfo

func (m *SubscribeToBacktestEventsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SubscribeToBacktestEventsRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *SubscribeToBacktestEventsRequest) GetPairSymbol() string {
	if m != nil {
		return m.PairSymbol
	}
	return ""
}

type SubscribeToBacktestEventsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeToBacktestEventsResponse) Reset()         { *m = SubscribeToBacktestEventsResponse{} }
func (m *SubscribeToBacktestEventsResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeToBacktestEventsResponse) ProtoMessage()    {}
func (*SubscribeToBacktestEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{5}
}

func (m *SubscribeToBacktestEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeToBacktestEventsResponse.Unmarshal(m, b)
}
func (m *SubscribeToBacktestEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeToBacktestEventsResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeToBacktestEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeToBacktestEventsResponse.Merge(m, src)
}
func (m *SubscribeToBacktestEventsResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeToBacktestEventsResponse.Size(m)
}
func (m *SubscribeToBacktestEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeToBacktestEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeToBacktestEventsResponse proto.InternalMessageInfo

type AdvanceBacktestRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvanceBacktestRequest) Reset()         { *m = AdvanceBacktestRequest{} }
func (m *AdvanceBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*AdvanceBacktestRequest) ProtoMessage()    {}
func (*AdvanceBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{6}
}

func (m *AdvanceBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvanceBacktestRequest.Unmarshal(m, b)
}
func (m *AdvanceBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvanceBacktestRequest.Marshal(b, m, deterministic)
}
func (m *AdvanceBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvanceBacktestRequest.Merge(m, src)
}
func (m *AdvanceBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_AdvanceBacktestRequest.Size(m)
}
func (m *AdvanceBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvanceBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdvanceBacktestRequest proto.InternalMessageInfo

func (m *AdvanceBacktestRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AdvanceBacktestResponse struct {
	Finished             bool     `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvanceBacktestResponse) Reset()         { *m = AdvanceBacktestResponse{} }
func (m *AdvanceBacktestResponse) String() string { return proto.CompactTextString(m) }
func (*AdvanceBacktestResponse) ProtoMessage()    {}
func (*AdvanceBacktestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{7}
}

func (m *AdvanceBacktestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvanceBacktestResponse.Unmarshal(m, b)
}
func (m *AdvanceBacktestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvanceBacktestResponse.Marshal(b, m, deterministic)
}
func (m *AdvanceBacktestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvanceBacktestResponse.Merge(m, src)
}
func (m *AdvanceBacktestResponse) XXX_Size() int {
	return xxx_messageInfo_AdvanceBacktestResponse.Size(m)
}
func (m *AdvanceBacktestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvanceBacktestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdvanceBacktestResponse proto.InternalMessageInfo

func (m *AdvanceBacktestResponse) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

type ListenBacktestRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenBacktestRequest) Reset()         { *m = ListenBacktestRequest{} }
func (m *ListenBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*ListenBacktestRequest) ProtoMessage()    {}
func (*ListenBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{8}
}

func (m *ListenBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenBacktestRequest.Unmarshal(m, b)
}
func (m *ListenBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenBacktestRequest.Marshal(b, m, deterministic)
}
func (m *ListenBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenBacktestRequest.Merge(m, src)
}
func (m *ListenBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_ListenBacktestRequest.Size(m)
}
func (m *ListenBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenBacktestRequest proto.InternalMessageInfo

func (m *ListenBacktestRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{9}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Event) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*AssetQuantity)(nil), "backtests.AssetQuantity")
	proto.RegisterType((*Account)(nil), "backtests.Account")
	proto.RegisterType((*CreateBacktestRequest)(nil), "backtests.CreateBacktestRequest")
	proto.RegisterType((*CreateBacktestResponse)(nil), "backtests.CreateBacktestResponse")
	proto.RegisterType((*SubscribeToBacktestEventsRequest)(nil), "backtests.SubscribeToBacktestEventsRequest")
	proto.RegisterType((*SubscribeToBacktestEventsResponse)(nil), "backtests.SubscribeToBacktestEventsResponse")
	proto.RegisterType((*AdvanceBacktestRequest)(nil), "backtests.AdvanceBacktestRequest")
	proto.RegisterType((*AdvanceBacktestResponse)(nil), "backtests.AdvanceBacktestResponse")
	proto.RegisterType((*ListenBacktestRequest)(nil), "backtests.ListenBacktestRequest")
	proto.RegisterType((*Event)(nil), "backtests.Event")
}

func init() { proto.RegisterFile("backtests.proto", fileDescriptor_f20790a094d31fce) }

var fileDescriptor_f20790a094d31fce = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0x93, 0x7c, 0x4d, 0x3c, 0xfd, 0x9a, 0x56, 0x2b, 0x95, 0x3a, 0x16, 0x08, 0xd7, 0xbd,
	0xc0, 0x12, 0x28, 0xa9, 0x8a, 0xb8, 0x46, 0x09, 0x42, 0x02, 0x84, 0x10, 0x38, 0x95, 0x90, 0x7a,
	0x63, 0xd6, 0xeb, 0x21, 0x5d, 0x15, 0xaf, 0x5d, 0xef, 0x26, 0x34, 0xcf, 0xc0, 0x5b, 0xf1, 0x64,
	0xc8, 0xeb, 0x9f, 0x3a, 0x69, 0x48, 0xb9, 0xf3, 0x9c, 0x39, 0x7b, 0x66, 0xce, 0xcc, 0xc8, 0x70,
	0x10, 0x52, 0x76, 0xad, 0x50, 0x2a, 0x39, 0x4c, 0xb3, 0x44, 0x25, 0xc4, 0xac, 0x01, 0xf7, 0x03,
	0xec, 0x8f, 0xa5, 0x44, 0xf5, 0x65, 0x4e, 0x85, 0xe2, 0x6a, 0x49, 0x9e, 0x00, 0xd0, 0x1c, 0x08,
	0x04, 0x8d, 0xd1, 0x32, 0x1c, 0xc3, 0x33, 0x7d, 0x53, 0x23, 0x9f, 0x68, 0x8c, 0xc4, 0x86, 0xde,
	0x4d, 0x49, 0xb5, 0x5a, 0x8e, 0xe1, 0xb5, 0xfc, 0x3a, 0x76, 0xbf, 0x41, 0x77, 0xcc, 0x58, 0x32,
	0x17, 0x8a, 0x9c, 0xc2, 0x3e, 0xde, 0xb2, 0x2b, 0x2a, 0x66, 0xd8, 0x14, 0xfa, 0xbf, 0x02, 0xb5,
	0xd6, 0x19, 0xec, 0x6a, 0x61, 0x69, 0xb5, 0x9c, 0xb6, 0xb7, 0x77, 0x6e, 0x0d, 0xef, 0x1a, 0x5d,
	0x69, 0xca, 0x2f, 0x79, 0xee, 0x6f, 0x03, 0x8e, 0xde, 0x64, 0x48, 0x15, 0x4e, 0x4a, 0xa6, 0x8f,
	0x37, 0x73, 0x94, 0x8a, 0x0c, 0xa1, 0x47, 0x8b, 0xda, 0xd2, 0x32, 0xb4, 0x1a, 0x69, 0xaa, 0x15,
	0x29, 0xbf, 0xe6, 0xe4, 0x36, 0xa5, 0xa2, 0x99, 0x0a, 0x14, 0x8f, 0x51, 0x3b, 0x31, 0x7d, 0x53,
	0x23, 0x17, 0x3c, 0x46, 0x32, 0x80, 0x1e, 0x8a, 0xa8, 0x48, 0xb6, 0x75, 0xb2, 0x8b, 0x22, 0xd2,
	0xa9, 0xd7, 0xf0, 0x58, 0x22, 0x4b, 0x44, 0x24, 0x83, 0x10, 0xd5, 0x4f, 0x44, 0x11, 0xa4, 0x19,
	0x67, 0x18, 0xe0, 0x02, 0xf3, 0xea, 0x1d, 0xc7, 0xf0, 0x3a, 0xfe, 0xa0, 0xe4, 0x4c, 0x0a, 0xca,
	0xe7, 0x9c, 0xf1, 0x56, 0x13, 0x5c, 0x0f, 0x1e, 0xad, 0x7b, 0x90, 0x69, 0x22, 0x24, 0x92, 0x3e,
	0xb4, 0x78, 0xa4, 0x47, 0xd5, 0xf1, 0x5b, 0x3c, 0x72, 0x13, 0x70, 0xa6, 0xf3, 0x50, 0xb2, 0x8c,
	0x87, 0x78, 0x91, 0x54, 0xf4, 0x42, 0xa6, 0x32, 0xbe, 0xf6, 0x26, 0x5f, 0x50, 0x35, 0xe4, 0xd2,
	0x56, 0x1d, 0x93, 0xa7, 0xb0, 0x97, 0x52, 0x9e, 0x05, 0x72, 0x19, 0x87, 0xc9, 0x8f, 0xd2, 0x18,
	0xe4, 0xd0, 0x54, 0x23, 0xee, 0x29, 0x9c, 0x6c, 0x29, 0x58, 0x74, 0x99, 0xf7, 0x3f, 0x8e, 0x16,
	0x54, 0xb0, 0x7b, 0x4b, 0x58, 0xef, 0xff, 0x15, 0x1c, 0xdf, 0x63, 0x96, 0x56, 0x6d, 0xe8, 0x7d,
	0xe7, 0x82, 0xcb, 0x2b, 0x2c, 0x1e, 0xf4, 0xfc, 0x3a, 0x76, 0x9f, 0xc1, 0xd1, 0x47, 0x2e, 0x15,
	0x8a, 0x87, 0xf4, 0xdf, 0xc3, 0x7f, 0xba, 0x37, 0x42, 0xa0, 0xa3, 0x96, 0x69, 0x75, 0x65, 0xfa,
	0x5b, 0x63, 0x77, 0xbb, 0xd5, 0xdf, 0xc4, 0x82, 0x2e, 0x4b, 0x84, 0x42, 0xa1, 0xaa, 0xad, 0x96,
	0xe1, 0xf9, 0xaf, 0x36, 0x1c, 0x56, 0xe5, 0xe4, 0x14, 0xb3, 0x05, 0x67, 0x48, 0xbe, 0x42, 0x7f,
	0x75, 0x53, 0xc4, 0x69, 0x1c, 0xd5, 0xc6, 0x43, 0xb4, 0x4f, 0xb6, 0x30, 0xca, 0x01, 0xee, 0x90,
	0x5b, 0x18, 0xfc, 0x75, 0xce, 0xe4, 0x79, 0x43, 0xe1, 0xa1, 0xf5, 0xdb, 0x2f, 0xfe, 0x8d, 0x5c,
	0x57, 0x7e, 0x07, 0xfd, 0xd5, 0xd9, 0xae, 0x58, 0xda, 0x38, 0x76, 0xfb, 0xb0, 0xc1, 0xd0, 0x82,
	0xee, 0xce, 0x99, 0x41, 0x2e, 0xe1, 0x60, 0x6d, 0xb9, 0xa4, 0xe9, 0x7d, 0xf3, 0x89, 0xd8, 0xee,
	0x36, 0x4a, 0xd5, 0xe5, 0x64, 0x70, 0x79, 0x3c, 0x4a, 0xaf, 0x67, 0xa3, 0x19, 0x0a, 0xfd, 0xc7,
	0x1a, 0xd5, 0x8f, 0xc2, 0x5d, 0x0d, 0xbc, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x79, 0xe1,
	0xf8, 0xd5, 0x04, 0x00, 0x00,
}
