// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backtests.proto

package backtests

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AssetQuantity struct {
	AssetName            string   `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Quantity             float32  `protobuf:"fixed32,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetQuantity) Reset()         { *m = AssetQuantity{} }
func (m *AssetQuantity) String() string { return proto.CompactTextString(m) }
func (*AssetQuantity) ProtoMessage()    {}
func (*AssetQuantity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{0}
}

func (m *AssetQuantity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetQuantity.Unmarshal(m, b)
}
func (m *AssetQuantity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetQuantity.Marshal(b, m, deterministic)
}
func (m *AssetQuantity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetQuantity.Merge(m, src)
}
func (m *AssetQuantity) XXX_Size() int {
	return xxx_messageInfo_AssetQuantity.Size(m)
}
func (m *AssetQuantity) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetQuantity.DiscardUnknown(m)
}

var xxx_messageInfo_AssetQuantity proto.InternalMessageInfo

func (m *AssetQuantity) GetAssetName() string {
	if m != nil {
		return m.AssetName
	}
	return ""
}

func (m *AssetQuantity) GetQuantity() float32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type Account struct {
	Exchange             string           `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Assets               []*AssetQuantity `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Account) GetAssets() []*AssetQuantity {
	if m != nil {
		return m.Assets
	}
	return nil
}

type CreateBacktestRequest struct {
	Accounts                  []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	StartTime                 string     `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                   string     `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SecondsBetweenPriceEvents uint64     `protobuf:"varint,4,opt,name=seconds_between_price_events,json=secondsBetweenPriceEvents,proto3" json:"seconds_between_price_events,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}   `json:"-"`
	XXX_unrecognized          []byte     `json:"-"`
	XXX_sizecache             int32      `json:"-"`
}

func (m *CreateBacktestRequest) Reset()         { *m = CreateBacktestRequest{} }
func (m *CreateBacktestRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestRequest) ProtoMessage()    {}
func (*CreateBacktestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{2}
}

func (m *CreateBacktestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestRequest.Unmarshal(m, b)
}
func (m *CreateBacktestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestRequest.Marshal(b, m, deterministic)
}
func (m *CreateBacktestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestRequest.Merge(m, src)
}
func (m *CreateBacktestRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestRequest.Size(m)
}
func (m *CreateBacktestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestRequest proto.InternalMessageInfo

func (m *CreateBacktestRequest) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *CreateBacktestRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreateBacktestRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CreateBacktestRequest) GetSecondsBetweenPriceEvents() uint64 {
	if m != nil {
		return m.SecondsBetweenPriceEvents
	}
	return 0
}

type CreateBacktestResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBacktestResponse) Reset()         { *m = CreateBacktestResponse{} }
func (m *CreateBacktestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBacktestResponse) ProtoMessage()    {}
func (*CreateBacktestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f20790a094d31fce, []int{3}
}

func (m *CreateBacktestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBacktestResponse.Unmarshal(m, b)
}
func (m *CreateBacktestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBacktestResponse.Marshal(b, m, deterministic)
}
func (m *CreateBacktestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBacktestResponse.Merge(m, src)
}
func (m *CreateBacktestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBacktestResponse.Size(m)
}
func (m *CreateBacktestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBacktestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBacktestResponse proto.InternalMessageInfo

func (m *CreateBacktestResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*AssetQuantity)(nil), "backtests.AssetQuantity")
	proto.RegisterType((*Account)(nil), "backtests.Account")
	proto.RegisterType((*CreateBacktestRequest)(nil), "backtests.CreateBacktestRequest")
	proto.RegisterType((*CreateBacktestResponse)(nil), "backtests.CreateBacktestResponse")
}

func init() { proto.RegisterFile("backtests.proto", fileDescriptor_f20790a094d31fce) }

var fileDescriptor_f20790a094d31fce = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xeb, 0x40,
	0x14, 0x85, 0x5f, 0xd2, 0xd2, 0x36, 0xf7, 0xf1, 0xfa, 0x1e, 0x03, 0x4f, 0xd3, 0xa2, 0x10, 0xb3,
	0xca, 0xaa, 0x95, 0xfa, 0x03, 0xa4, 0x15, 0x37, 0x2e, 0x44, 0x47, 0xa1, 0xe0, 0x26, 0x4c, 0x27,
	0x97, 0x3a, 0x94, 0x4c, 0xd2, 0xcc, 0x6d, 0xd5, 0xbf, 0xe7, 0x2f, 0x93, 0x4c, 0xd2, 0xd8, 0x8a,
	0xb8, 0x9c, 0x73, 0xbe, 0x39, 0x77, 0xce, 0x65, 0xe0, 0xef, 0x42, 0xc8, 0x15, 0xa1, 0x21, 0x33,
	0xca, 0x8b, 0x8c, 0x32, 0xe6, 0x35, 0x42, 0x78, 0x03, 0x7f, 0xa6, 0xc6, 0x20, 0xdd, 0x6f, 0x84,
	0x26, 0x45, 0x6f, 0xec, 0x14, 0x40, 0x94, 0x42, 0xac, 0x45, 0x8a, 0xbe, 0x13, 0x38, 0x91, 0xc7,
	0x3d, 0xab, 0xdc, 0x8a, 0x14, 0xd9, 0x10, 0x7a, 0xeb, 0x1a, 0xf5, 0xdd, 0xc0, 0x89, 0x5c, 0xde,
	0x9c, 0xc3, 0x39, 0x74, 0xa7, 0x52, 0x66, 0x1b, 0x4d, 0x25, 0x86, 0xaf, 0xf2, 0x59, 0xe8, 0xe5,
	0x2e, 0xa3, 0x39, 0xb3, 0x73, 0xe8, 0xd8, 0x3c, 0xe3, 0xbb, 0x41, 0x2b, 0xfa, 0x3d, 0xf1, 0x47,
	0x9f, 0xef, 0x3b, 0x78, 0x0b, 0xaf, 0xb9, 0xf0, 0xdd, 0x81, 0xff, 0x57, 0x05, 0x0a, 0xc2, 0x59,
	0x4d, 0x72, 0x5c, 0x6f, 0xd0, 0x10, 0x1b, 0x41, 0x4f, 0x54, 0x23, 0x8d, 0xef, 0xd8, 0x34, 0xb6,
	0x9f, 0x56, 0x59, 0xbc, 0x61, 0xca, 0x76, 0x86, 0x44, 0x41, 0x31, 0xa9, 0x14, 0x6d, 0x01, 0x8f,
	0x7b, 0x56, 0x79, 0x54, 0x29, 0xb2, 0x01, 0xf4, 0x50, 0x27, 0x95, 0xd9, 0xb2, 0x66, 0x17, 0x75,
	0x62, 0xad, 0x4b, 0x38, 0x31, 0x28, 0x33, 0x9d, 0x98, 0x78, 0x81, 0xf4, 0x82, 0xa8, 0xe3, 0xbc,
	0x50, 0x12, 0x63, 0xdc, 0x62, 0x39, 0xbd, 0x1d, 0x38, 0x51, 0x9b, 0x0f, 0x6a, 0x66, 0x56, 0x21,
	0x77, 0x25, 0x71, 0x6d, 0x81, 0x30, 0x82, 0xa3, 0xaf, 0x1d, 0x4c, 0x9e, 0x69, 0x83, 0xac, 0x0f,
	0xae, 0x4a, 0xec, 0x9a, 0xda, 0xdc, 0x55, 0xc9, 0x64, 0x05, 0xff, 0x76, 0x8c, 0x79, 0xc0, 0x62,
	0xab, 0x24, 0xb2, 0x39, 0xf4, 0x0f, 0x6f, 0xb3, 0x60, 0xaf, 0xe8, 0xb7, 0xcb, 0x19, 0x9e, 0xfd,
	0x40, 0x54, 0xa3, 0xc3, 0x5f, 0xb3, 0xc1, 0xd3, 0xf1, 0x38, 0x5f, 0x2d, 0xc7, 0x4b, 0xd4, 0xf6,
	0x73, 0x8c, 0x9b, 0x3b, 0x8b, 0x8e, 0x15, 0x2e, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x85, 0xaa,
	0x26, 0xe4, 0x40, 0x02, 0x00, 0x00,
}
