# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import ticks_pb2 as ticks__pb2


class TicksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenSymbol = channel.unary_stream(
                '/ticks.TicksService/ListenSymbol',
                request_serializer=ticks__pb2.ListenSymbolRequest.SerializeToString,
                response_deserializer=ticks__pb2.Tick.FromString,
                )


class TicksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListenSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenSymbol': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenSymbol,
                    request_deserializer=ticks__pb2.ListenSymbolRequest.FromString,
                    response_serializer=ticks__pb2.Tick.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticks.TicksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListenSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ticks.TicksService/ListenSymbol',
            ticks__pb2.ListenSymbolRequest.SerializeToString,
            ticks__pb2.Tick.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
