# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bticks.proto\x12\x05ticks\"<\n\x13ListenSymbolRequest\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x13\n\x0bpair_symbol\x18\x02 \x01(\t\"J\n\x04Tick\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x13\n\x0bpair_symbol\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x32K\n\x0cTicksService\x12;\n\x0cListenSymbol\x12\x1a.ticks.ListenSymbolRequest\x1a\x0b.ticks.Tick\"\x00\x30\x01\x42\x15Z\x13/pkg/genproto/ticksb\x06proto3')



_LISTENSYMBOLREQUEST = DESCRIPTOR.message_types_by_name['ListenSymbolRequest']
_TICK = DESCRIPTOR.message_types_by_name['Tick']
ListenSymbolRequest = _reflection.GeneratedProtocolMessageType('ListenSymbolRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTENSYMBOLREQUEST,
  '__module__' : 'ticks_pb2'
  # @@protoc_insertion_point(class_scope:ticks.ListenSymbolRequest)
  })
_sym_db.RegisterMessage(ListenSymbolRequest)

Tick = _reflection.GeneratedProtocolMessageType('Tick', (_message.Message,), {
  'DESCRIPTOR' : _TICK,
  '__module__' : 'ticks_pb2'
  # @@protoc_insertion_point(class_scope:ticks.Tick)
  })
_sym_db.RegisterMessage(Tick)

_TICKSSERVICE = DESCRIPTOR.services_by_name['TicksService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\023/pkg/genproto/ticks'
  _LISTENSYMBOLREQUEST._serialized_start=22
  _LISTENSYMBOLREQUEST._serialized_end=82
  _TICK._serialized_start=84
  _TICK._serialized_end=158
  _TICKSSERVICE._serialized_start=160
  _TICKSSERVICE._serialized_end=235
# @@protoc_insertion_point(module_scope)
