// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assets.proto

package assets

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Asset struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type CreateAssetsRequest struct {
	Assets               []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAssetsRequest) Reset()         { *m = CreateAssetsRequest{} }
func (m *CreateAssetsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAssetsRequest) ProtoMessage()    {}
func (*CreateAssetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

func (m *CreateAssetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssetsRequest.Unmarshal(m, b)
}
func (m *CreateAssetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssetsRequest.Marshal(b, m, deterministic)
}
func (m *CreateAssetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssetsRequest.Merge(m, src)
}
func (m *CreateAssetsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAssetsRequest.Size(m)
}
func (m *CreateAssetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssetsRequest proto.InternalMessageInfo

func (m *CreateAssetsRequest) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

type CreateAssetsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAssetsResponse) Reset()         { *m = CreateAssetsResponse{} }
func (m *CreateAssetsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAssetsResponse) ProtoMessage()    {}
func (*CreateAssetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{2}
}

func (m *CreateAssetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAssetsResponse.Unmarshal(m, b)
}
func (m *CreateAssetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAssetsResponse.Marshal(b, m, deterministic)
}
func (m *CreateAssetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAssetsResponse.Merge(m, src)
}
func (m *CreateAssetsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAssetsResponse.Size(m)
}
func (m *CreateAssetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAssetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAssetsResponse proto.InternalMessageInfo

type ReadAssetsRequest struct {
	Symbols              []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAssetsRequest) Reset()         { *m = ReadAssetsRequest{} }
func (m *ReadAssetsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAssetsRequest) ProtoMessage()    {}
func (*ReadAssetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{3}
}

func (m *ReadAssetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAssetsRequest.Unmarshal(m, b)
}
func (m *ReadAssetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAssetsRequest.Marshal(b, m, deterministic)
}
func (m *ReadAssetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAssetsRequest.Merge(m, src)
}
func (m *ReadAssetsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAssetsRequest.Size(m)
}
func (m *ReadAssetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAssetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAssetsRequest proto.InternalMessageInfo

func (m *ReadAssetsRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type ReadAssetsResponse struct {
	Assets               []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAssetsResponse) Reset()         { *m = ReadAssetsResponse{} }
func (m *ReadAssetsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAssetsResponse) ProtoMessage()    {}
func (*ReadAssetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{4}
}

func (m *ReadAssetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAssetsResponse.Unmarshal(m, b)
}
func (m *ReadAssetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAssetsResponse.Marshal(b, m, deterministic)
}
func (m *ReadAssetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAssetsResponse.Merge(m, src)
}
func (m *ReadAssetsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAssetsResponse.Size(m)
}
func (m *ReadAssetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAssetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAssetsResponse proto.InternalMessageInfo

func (m *ReadAssetsResponse) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func init() {
	proto.RegisterType((*Asset)(nil), "assets.Asset")
	proto.RegisterType((*CreateAssetsRequest)(nil), "assets.CreateAssetsRequest")
	proto.RegisterType((*CreateAssetsResponse)(nil), "assets.CreateAssetsResponse")
	proto.RegisterType((*ReadAssetsRequest)(nil), "assets.ReadAssetsRequest")
	proto.RegisterType((*ReadAssetsResponse)(nil), "assets.ReadAssetsResponse")
}

func init() { proto.RegisterFile("assets.proto", fileDescriptor_610ca40ce07a87fe) }

var fileDescriptor_610ca40ce07a87fe = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2c, 0x2e, 0x4e,
	0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xe4, 0xb9, 0x58,
	0x1d, 0x41, 0x2c, 0x21, 0x31, 0x2e, 0xb6, 0xe2, 0xca, 0xdc, 0xa4, 0xfc, 0x1c, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x28, 0x4f, 0xc9, 0x86, 0x4b, 0xd8, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15,
	0xac, 0xac, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x95, 0x0b, 0x6a, 0x82, 0x04,
	0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0xaf, 0x1e, 0xd4, 0x78, 0xb0, 0xb2, 0x20, 0x98, 0xf1, 0x62,
	0x5c, 0x22, 0xa8, 0xba, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x95, 0x74, 0xb9, 0x04, 0x83, 0x52,
	0x13, 0x53, 0x50, 0xcd, 0x94, 0xe0, 0x62, 0x87, 0x58, 0x0a, 0x31, 0x94, 0x33, 0x08, 0xc6, 0x55,
	0xb2, 0xe6, 0x12, 0x42, 0x56, 0x0e, 0x31, 0x84, 0x48, 0x37, 0x18, 0x2d, 0x66, 0xe4, 0xe2, 0x85,
	0xe8, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xf2, 0xe6, 0xe2, 0x41, 0x76, 0x95, 0x90,
	0x34, 0x4c, 0x23, 0x16, 0x9f, 0x4a, 0xc9, 0x60, 0x97, 0x84, 0x7a, 0x84, 0x41, 0xc8, 0x95, 0x8b,
	0x0b, 0xe1, 0x36, 0x21, 0x49, 0x98, 0x6a, 0x0c, 0xef, 0x49, 0x49, 0x61, 0x93, 0x82, 0x19, 0xe3,
	0x24, 0x16, 0x25, 0xa2, 0x5f, 0x90, 0x9d, 0xae, 0x9f, 0x9e, 0x9a, 0x07, 0x8e, 0x21, 0x7d, 0x88,
	0xe2, 0x24, 0x36, 0x30, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xab, 0x93, 0x4a, 0xbf, 0xbf,
	0x01, 0x00, 0x00,
}
