// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pairs.proto

package pairs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pair struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseAssetSymbol      string   `protobuf:"bytes,2,opt,name=base_asset_symbol,json=baseAssetSymbol,proto3" json:"base_asset_symbol,omitempty"`
	QuoteAssetSymbol     string   `protobuf:"bytes,3,opt,name=quote_asset_symbol,json=quoteAssetSymbol,proto3" json:"quote_asset_symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d0f7d2d986144b, []int{0}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Pair) GetBaseAssetSymbol() string {
	if m != nil {
		return m.BaseAssetSymbol
	}
	return ""
}

func (m *Pair) GetQuoteAssetSymbol() string {
	if m != nil {
		return m.QuoteAssetSymbol
	}
	return ""
}

type CreatePairsRequest struct {
	Pairs                []*Pair  `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePairsRequest) Reset()         { *m = CreatePairsRequest{} }
func (m *CreatePairsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePairsRequest) ProtoMessage()    {}
func (*CreatePairsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d0f7d2d986144b, []int{1}
}

func (m *CreatePairsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePairsRequest.Unmarshal(m, b)
}
func (m *CreatePairsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePairsRequest.Marshal(b, m, deterministic)
}
func (m *CreatePairsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePairsRequest.Merge(m, src)
}
func (m *CreatePairsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePairsRequest.Size(m)
}
func (m *CreatePairsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePairsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePairsRequest proto.InternalMessageInfo

func (m *CreatePairsRequest) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type CreatePairsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePairsResponse) Reset()         { *m = CreatePairsResponse{} }
func (m *CreatePairsResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePairsResponse) ProtoMessage()    {}
func (*CreatePairsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d0f7d2d986144b, []int{2}
}

func (m *CreatePairsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePairsResponse.Unmarshal(m, b)
}
func (m *CreatePairsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePairsResponse.Marshal(b, m, deterministic)
}
func (m *CreatePairsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePairsResponse.Merge(m, src)
}
func (m *CreatePairsResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePairsResponse.Size(m)
}
func (m *CreatePairsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePairsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePairsResponse proto.InternalMessageInfo

type ReadPairsRequest struct {
	Symbols              []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPairsRequest) Reset()         { *m = ReadPairsRequest{} }
func (m *ReadPairsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadPairsRequest) ProtoMessage()    {}
func (*ReadPairsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d0f7d2d986144b, []int{3}
}

func (m *ReadPairsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPairsRequest.Unmarshal(m, b)
}
func (m *ReadPairsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPairsRequest.Marshal(b, m, deterministic)
}
func (m *ReadPairsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPairsRequest.Merge(m, src)
}
func (m *ReadPairsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadPairsRequest.Size(m)
}
func (m *ReadPairsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPairsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPairsRequest proto.InternalMessageInfo

func (m *ReadPairsRequest) GetSymbols() []string {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type ReadPairsResponse struct {
	Pairs                []*Pair  `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPairsResponse) Reset()         { *m = ReadPairsResponse{} }
func (m *ReadPairsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPairsResponse) ProtoMessage()    {}
func (*ReadPairsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d0f7d2d986144b, []int{4}
}

func (m *ReadPairsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPairsResponse.Unmarshal(m, b)
}
func (m *ReadPairsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPairsResponse.Marshal(b, m, deterministic)
}
func (m *ReadPairsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPairsResponse.Merge(m, src)
}
func (m *ReadPairsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPairsResponse.Size(m)
}
func (m *ReadPairsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPairsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPairsResponse proto.InternalMessageInfo

func (m *ReadPairsResponse) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func init() {
	proto.RegisterType((*Pair)(nil), "pairs.Pair")
	proto.RegisterType((*CreatePairsRequest)(nil), "pairs.CreatePairsRequest")
	proto.RegisterType((*CreatePairsResponse)(nil), "pairs.CreatePairsResponse")
	proto.RegisterType((*ReadPairsRequest)(nil), "pairs.ReadPairsRequest")
	proto.RegisterType((*ReadPairsResponse)(nil), "pairs.ReadPairsResponse")
}

func init() { proto.RegisterFile("pairs.proto", fileDescriptor_09d0f7d2d986144b) }

var fileDescriptor_09d0f7d2d986144b = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xd5, 0x4a, 0x26, 0x82, 0xed, 0x94, 0x6a, 0xcc, 0xa9, 0xe6, 0x54, 0xa4, 0x34,
	0x50, 0x41, 0xaf, 0xfe, 0x01, 0xcf, 0xb2, 0xbd, 0x79, 0x29, 0x1b, 0x1d, 0x4a, 0x50, 0xbb, 0xe9,
	0xce, 0x56, 0xf4, 0x9b, 0xf8, 0x71, 0x25, 0xbb, 0x5b, 0x49, 0x1b, 0x0f, 0x3d, 0xbe, 0x7d, 0xbf,
	0x79, 0xf3, 0x86, 0x85, 0xa8, 0x94, 0x85, 0xe6, 0x71, 0xa9, 0x95, 0x51, 0x78, 0x68, 0x45, 0xfa,
	0x05, 0x07, 0x4f, 0xb2, 0xd0, 0x78, 0x0a, 0x6d, 0xfe, 0xfe, 0xc8, 0xd5, 0x7b, 0x1c, 0x0c, 0x82,
	0x61, 0x28, 0xbc, 0xc2, 0x4b, 0xe8, 0xe6, 0x92, 0x69, 0x26, 0x99, 0xc9, 0xcc, 0x3c, 0xb2, 0x6f,
	0x91, 0x93, 0xca, 0xb8, 0xab, 0xde, 0xa7, 0x8e, 0x1d, 0x01, 0x2e, 0x57, 0xca, 0x6c, 0xc1, 0x2d,
	0x0b, 0x77, 0xac, 0x53, 0xa3, 0xd3, 0x1b, 0xc0, 0x07, 0x4d, 0xd2, 0x50, 0xb5, 0x9f, 0x05, 0x2d,
	0x57, 0xc4, 0x06, 0x2f, 0xc0, 0x15, 0x8b, 0x83, 0x41, 0x6b, 0x18, 0x4d, 0xa2, 0xb1, 0xeb, 0x5c,
	0x31, 0xc2, 0x57, 0xee, 0x43, 0x6f, 0x63, 0x90, 0x4b, 0xb5, 0x60, 0x4a, 0x47, 0xd0, 0x11, 0x24,
	0x5f, 0x37, 0xd2, 0x62, 0x38, 0x72, 0x2d, 0x5c, 0x5e, 0x28, 0xd6, 0x32, 0xbd, 0x86, 0x6e, 0x8d,
	0x76, 0x11, 0x3b, 0x2c, 0x9f, 0xfc, 0x04, 0x70, 0x6c, 0x87, 0xa6, 0xa4, 0x3f, 0x8b, 0x17, 0xc2,
	0x47, 0x88, 0x6a, 0x6d, 0xf0, 0xdc, 0xcf, 0x34, 0x4f, 0x4b, 0x92, 0xff, 0x2c, 0x5f, 0x7e, 0x0f,
	0x6f, 0x21, 0xfc, 0x2b, 0x84, 0x67, 0x1e, 0xdd, 0x3e, 0x28, 0x89, 0x9b, 0xc6, 0x3a, 0xe1, 0xbe,
	0xff, 0xdc, 0xcb, 0xca, 0xb7, 0x79, 0x36, 0xa7, 0x85, 0xfd, 0xe2, 0xcc, 0xa2, 0x79, 0xdb, 0x8a,
	0xab, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x7e, 0x81, 0x59, 0xfe, 0x01, 0x00, 0x00,
}
